# Generated by Django 3.0 on 2020-08-09 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_info', '0002_assignment_course_exam_queryhistory_question_teacher_teachingassistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='deleted at')),
                ('user_id', models.IntegerField()),
                ('score', models.FloatField()),
                ('suggestion', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_info.Course', verbose_name='the related course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
