# Generated by Django 3.1 on 2020-08-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_info', '0004_auto_20200810_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='query_title',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
